const assert=require('node:assert/strict');
const http=require('node:http');
const test=require('node:test');
const {WebSocket}=require('ws');
const {createDashboardWebSocketHub}=require('../src/dashboard/webSocketHub');
const {createTriggerExecutionService}=require('../src/triggers/triggerExecutionService');
const {createTargetPolicyService}=require('../src/triggers/targetPolicyService');
const {createBotCommandService}=require('../src/commands/botCommandService');
const {ValidationError}=require('../src/validation/domain');

function requestRepository(){const requests=new Map();return {requests,
  async createRequest(value){const row={...value,id:`request-${requests.size+1}`,status:'pending'};requests.set(row.id,row);return row;},
  async claimRequest(userId,id,now){const row=requests.get(id);if(!row||row.userId!==userId||row.status!=='pending'||row.expiresAt<=now)return null;row.status='executing';return row;},
  async finishRequest(id,status){requests.get(id).status=status;},
  async rejectRequest(userId,id,now){const row=requests.get(id);if(!row||row.userId!==userId||row.status!=='pending'||row.expiresAt<=now)return null;row.status='rejected';return row;},
  async addAudit(){},async listPendingRequests(userId){return [...requests.values()].filter(row=>row.userId===userId&&row.status==='pending');}};}
function open(url,cookie){return new Promise((resolve,reject)=>{const socket=new WebSocket(url,{headers:{cookie}});const messages=[];socket.on('message',data=>messages.push(JSON.parse(data)));socket.once('open',()=>resolve({socket,messages}));socket.once('error',reject);});}

test('real trigger pending and resolution events are live, user-isolated, durable, and single-execution',async t=>{const auth={authenticate:async cookie=>({userId:String(cookie).includes('user-a')?'user-a':'user-b'})};const hub=createDashboardWebSocketHub({auth});const server=http.createServer();hub.attach(server);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await hub.close();await new Promise(resolve=>server.close(resolve));});const url=`ws://127.0.0.1:${server.address().port}/ws`;const a=await open(url,'user-a');const b=await open(url,'user-b');await new Promise(resolve=>setTimeout(resolve,20));a.messages.length=0;b.messages.length=0;
  const repository=requestRepository();let executions=0;const service=createTriggerExecutionService({repository,policyService:{get:async()=>({blockchainTrigger:'manual',socialTrigger:'manual',humanVerification:'on',dontAskAgain:false})},prepareExecution:async event=>({preview:{contractAddress:event.address,methodSignature:'mint(uint256)',arguments:[{name:'quantity',value:'1'}]},executionPayload:event}),execute:async()=>{executions++;return {state:'submitted',intentId:'intent',txHash:'0x1'};},notify:async()=>{},onPending:(userId,request)=>hub.broadcastToUser(userId,{type:'confirmation.pending',request}),onResolved:(userId,value)=>hub.broadcastToUser(userId,{type:'confirmation.resolved',...value})});
  const result=await service.handle({id:'event-1',userId:'user-a',targetType:'social_rule',targetId:'123e4567-e89b-42d3-a456-426614174000',triggerSource:'social-triggered',address:'0x0000000000000000000000000000000000000001'});await new Promise(resolve=>setTimeout(resolve,20));assert.equal(a.messages[0].type,'confirmation.pending');assert.equal(b.messages.length,0);assert.equal((await repository.listPendingRequests('user-a')).length,1);
  await service.confirm('user-a',result.request.id,'CONFIRM');await assert.rejects(service.confirm('user-a',result.request.id,'CONFIRM'),/already used/);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(executions,1);assert.equal(a.messages.at(-1).type,'confirmation.resolved');assert.equal((await repository.listPendingRequests('user-a')).length,0);
  const rejected=await service.handle({id:'event-2',userId:'user-a',targetType:'social_rule',targetId:'123e4567-e89b-42d3-a456-426614174000',triggerSource:'social-triggered',address:'0x0000000000000000000000000000000000000001'});await service.confirm('user-a',rejected.request.id,'REJECT');await new Promise(resolve=>setTimeout(resolve,20));assert.equal(executions,1);assert.equal(a.messages.at(-1).status,'rejected');assert.equal((await repository.listPendingRequests('user-a')).length,0);a.socket.close();b.socket.close();});

function policyFixture(){const policies=new Map(),challenges=new Map();let count=0;const key=(u,t,i)=>`${u}:${t}:${i}`;const repository={get:async(u,t,i)=>policies.get(key(u,t,i))||null,save:async value=>(policies.set(key(value.userId,value.targetType,value.targetId),value),value),reset:async(u,t,i)=>policies.delete(key(u,t,i)),createChallenge:async value=>{const id=`challenge-${++count}`;challenges.set(id,{...value,target_type:value.targetType,target_id:value.targetId,dont_ask_again:value.dontAskAgain});return id;},consumeChallenge:async(u,id,now)=>{const value=challenges.get(id);if(!value||value.userId!==u||value.expiresAt<=now||value.used)return null;value.used=true;return value;}};return {service:createTargetPolicyService({repository,targetExists:async(userId,type,id)=>userId==='user-a'&&['123e4567-e89b-42d3-a456-426614174001','123e4567-e89b-42d3-a456-426614174002'].includes(id),governanceRepository:{getEffectiveGovernance:async()=>({})}})};}
test('dashboard bypass uses shared explicit challenge and dont-ask-again stays target scoped',async()=>{const {service}=policyFixture();await assert.rejects(service.save('user-a',{targetType:'sniper',targetId:'123e4567-e89b-42d3-a456-426614174001',humanVerification:'bypassed'}),error=>error instanceof ValidationError&&error.issues.some(issue=>/explicit confirmation/.test(issue.message)));const requested=await service.requestBypass('user-a',{targetType:'sniper',targetId:'123e4567-e89b-42d3-a456-426614174001',dontAskAgain:true});assert.equal(requested.requiresConfirmation,true);await assert.rejects(service.confirmBypass('user-a',{challengeId:requested.challengeId,confirmation:'yes'}),error=>error instanceof ValidationError&&error.issues.some(issue=>/CONFIRM/.test(issue.message)));const enabled=await service.confirmBypass('user-a',{challengeId:requested.challengeId,confirmation:'CONFIRM'});assert.equal(enabled.humanVerification,'bypassed');assert.equal(enabled.dontAskAgain,true);const other=await service.get('user-a','sniper','123e4567-e89b-42d3-a456-426614174002');assert.equal(other.humanVerification,'on');assert.equal(other.dontAskAgain,false);});

test('shared sniper command rejects values above M7a governance for every surface',async()=>{const state={wallets:[{id:1,userId:'user-a',label:'alpha',chain:'ethereum'}],tasks:[],activity:[],pnl:[],snipers:[]};const service=createBotCommandService({storage:{},schedulerRepository:{},providerService:{},governance:{},adminCommands:{},sniperService:{validateCreate:value=>({...value,id:'123e4567-e89b-42d3-a456-426614174000',active:true,contractAllowlist:[],contractDenylist:[]})},socialWatchService:{},targetPolicyService:{},governanceRepository:{getEffectiveGovernance:async()=>({isOwner:false,maxTransactionValueWei:10000000000000000n,dailySpendingBudgetWei:20000000000000000n,gasCeilingGwei:50})},supportedChains:['ethereum'],chains:{ethereum:{}},encryptPrivateKey:()=>({}),getState:()=>state});await assert.rejects(service.createSniper('user-a',{label:'too high',walletLabel:'alpha',chain:'ethereum',maxValueETH:1,dailySpendingCapETH:.01,maxGasGwei:10}),error=>error instanceof ValidationError&&error.issues[0].field==='maxValueETH');});
