const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const test=require('node:test');
const express=require('express');
const {WebSocket}=require('ws');
const {createDashboardApi}=require('../src/dashboard/api');
const {createDashboardAuthService,SESSION_COOKIE,CSRF_COOKIE}=require('../src/dashboard/authService');
const {createDashboardWebSocketHub}=require('../src/dashboard/webSocketHub');
const {LinkCodeError}=require('../src/identity/identityService');
const {createCommandRateLimiter}=require('../src/security/botSecurity');

function fixture(){const sessions=new Map();let counter=0;const consumed=[];const identity={consumeDashboardLinkCode:async code=>{consumed.push(code);if(code!=='VALID')throw new LinkCodeError('specific internal reason');return 'user-a';}};
  const repository={create:async value=>{const id=`session-${++counter}`;sessions.set(id,{...value,sessionId:id});return id;},resolve:async tokenHash=>[...sessions.values()].find(value=>value.tokenHash===tokenHash&&!value.revoked)||null,
    revoke:async id=>{const value=sessions.get(id);if(!value||value.revoked)return false;value.revoked=true;return true;},revokeAll:async userId=>{let count=0;for(const value of sessions.values())if(value.userId===userId&&!value.revoked){value.revoked=true;count++;}return count;}};
  const auth=createDashboardAuthService({identity,repository});return {auth,consumed,sessions};}
function cookieValues(headers){const list=typeof headers.getSetCookie==='function'?headers.getSetCookie():headers.get('set-cookie').split(/,(?=\s*[^;,]+=)/);return Object.fromEntries(list.map(value=>{const [pair]=value.split(';');const index=pair.indexOf('=');return [pair.slice(0,index),decodeURIComponent(pair.slice(index+1))];}));}
async function appServer(t){const data=fixture();const api=createDashboardApi({auth:data.auth,identityRepository:{listLinkedAccounts:async()=>[{platform:'telegram',platformUserId:'42'}]},loginRateLimiter:createCommandRateLimiter()});const app=express();app.use(express.json());app.use(api.securityHeaders);app.post('/api/auth/login',api.login);app.post('/api/auth/logout',api.requireSession,api.requireCsrf,api.logout);app.get('/api/profile',api.requireSession,api.profile);const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));return {...data,base:`http://127.0.0.1:${server.address().port}`,server};}

test('invalid and expired-looking link codes return the same generic login error',async t=>{const {base}=await appServer(t);for(const code of ['INVALID','EXPIRED']){const response=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});assert.equal(response.status,401);assert.deepEqual(await response.json(),{error:'Invalid or expired login code'});}});
test('valid link code creates a working session and logout revokes it server-side',async t=>{const {base}=await appServer(t);const login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:'VALID'})});assert.equal(login.status,204);const setCookies=typeof login.headers.getSetCookie==='function'?login.headers.getSetCookie():[login.headers.get('set-cookie')];assert.ok(setCookies.some(value=>value.startsWith(`${SESSION_COOKIE}=`)&&/HttpOnly/i.test(value)&&/Secure/i.test(value)&&/SameSite=Strict/i.test(value)));assert.ok(setCookies.some(value=>value.startsWith(`${CSRF_COOKIE}=`)&&!/HttpOnly/i.test(value)&&/Secure/i.test(value)&&/SameSite=Strict/i.test(value)));const values=cookieValues(login.headers);const cookie=`${SESSION_COOKIE}=${values[SESSION_COOKIE]}; ${CSRF_COOKIE}=${values[CSRF_COOKIE]}`;assert.equal((await fetch(`${base}/api/profile`,{headers:{cookie}})).status,200);const noCsrf=await fetch(`${base}/api/auth/logout`,{method:'POST',headers:{cookie}});assert.equal(noCsrf.status,403);const logout=await fetch(`${base}/api/auth/logout`,{method:'POST',headers:{cookie,'x-csrf-token':values[CSRF_COOKIE]}});assert.equal(logout.status,204);assert.equal((await fetch(`${base}/api/profile`,{headers:{cookie}})).status,401);});
test('unauthenticated API requests are rejected with no-store security headers',async t=>{const {base}=await appServer(t);const response=await fetch(`${base}/api/profile`);assert.equal(response.status,401);assert.match(response.headers.get('cache-control'),/no-store/);assert.equal(response.headers.get('x-frame-options'),'DENY');assert.match(response.headers.get('content-security-policy'),/frame-ancestors 'none'/);});

function openSocket(url,cookie){return new Promise((resolve,reject)=>{const socket=new WebSocket(url,{headers:cookie?{Cookie:cookie}:{}});const messages=[];socket.on('message',value=>messages.push(JSON.parse(value.toString())));socket.once('open',()=>resolve({socket,messages}));socket.once('unexpected-response',(request,response)=>reject(Object.assign(new Error('rejected'),{statusCode:response.statusCode})));socket.once('error',reject);});}
function nextMessage(socket){return new Promise(resolve=>socket.once('message',value=>resolve(JSON.parse(value.toString()))));}
test('WebSocket rejects unauthenticated clients and isolates user broadcasts',async t=>{const sessions=new Map([['token-a',{userId:'user-a'}],['token-b',{userId:'user-b'}]]);const auth={authenticate:async header=>sessions.get(String(header||'').split('=')[1])||null};const hub=createDashboardWebSocketHub({auth});const server=http.createServer();hub.attach(server);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await hub.close();await new Promise(resolve=>server.close(resolve));});const url=`ws://127.0.0.1:${server.address().port}/ws`;
  await assert.rejects(openSocket(url),error=>error.statusCode===401);const a=await openSocket(url,`${SESSION_COOKIE}=token-a`);const b=await openSocket(url,`${SESSION_COOKIE}=token-b`);await new Promise(resolve=>setTimeout(resolve,10));assert.deepEqual(a.messages.shift(),{type:'connected'});assert.deepEqual(b.messages.shift(),{type:'connected'});const message=nextMessage(a.socket);hub.broadcastToUser('user-a',{type:'test',value:'only-a'});assert.deepEqual(await message,{type:'test',value:'only-a'});await new Promise(resolve=>setTimeout(resolve,30));assert.deepEqual(b.messages,[]);a.socket.close();b.socket.close();});

test('dashboard production bundle contains no server secrets or secret variable names',()=>{const root=path.join(__dirname,'..','public','dashboard');assert.equal(fs.existsSync(path.join(root,'index.html')),true,'dashboard must be built before tests');const content=fs.readdirSync(path.join(root,'assets')).map(name=>fs.readFileSync(path.join(root,'assets',name),'utf8')).join('\n');const forbidden=['ENCRYPTION_SECRET','DATABASE_URL','DISCORD_BOT_TOKEN','TELEGRAM_BOT_TOKEN','dev-encryption-key-7Qv9'];const envPath=path.join(__dirname,'..','.env');if(fs.existsSync(envPath)){const values=require('dotenv').parse(fs.readFileSync(envPath));for(const name of ['ENCRYPTION_SECRET','DISCORD_BOT_TOKEN','TELEGRAM_BOT_TOKEN','SOCIAL_OFFICIAL_API_TOKEN','SOCIAL_MANAGED_SERVICE_TOKEN'])if(values[name]?.length>=8)forbidden.push(values[name]);}for(const value of forbidden)assert.equal(content.includes(value),false,`bundle contains forbidden server value: ${value.startsWith('dev-')?value:'[redacted]'}`);});
