/* global FormData, URLSearchParams */
import React,{useCallback,useEffect,useState} from 'react';
import {api} from './shared.jsx';

function useLoad(path){const [data,setData]=useState(null);const [error,setError]=useState('');const load=useCallback(()=>api(path).then(setData).catch(value=>setError(value.message)),[path]);useEffect(()=>{load();},[load]);return {data,error,load};}
function Field({label,required=true,...props}){return <label>{label}<input required={required} {...props}/></label>}
function Select({label,options=[],...props}){return <label>{label}<select required {...props}>{options.map(value=><option key={value} value={value}>{value}</option>)}</select></label>}
function Form({title,note,onSubmit,children}){return <form className="panel form" onSubmit={onSubmit}><h2>{title}</h2>{note&&<p>{note}</p>}<div className="fields">{children}</div></form>}
function identity(user){return user.linkedAccounts?.[0]||null;}
function simulation(value){return value===true?'forced':value===false?'optional':'inherit';}
function ConfirmAction({label,warning,onConfirm}){const [open,setOpen]=useState(false);const [text,setText]=useState('');return open?<div className="warning-box"><strong>{warning}</strong><p>Type CONFIRM exactly to continue.</p><input aria-label={`${label} confirmation`} value={text} onChange={event=>setText(event.target.value)} autoComplete="off"/><div className="actions"><button className="danger" disabled={text!=='CONFIRM'} onClick={()=>{onConfirm();setOpen(false);setText('');}}>Confirm {label}</button><button className="quiet" onClick={()=>setOpen(false)}>Cancel</button></div></div>:<button className="danger small" onClick={()=>setOpen(true)}>{label}</button>}

function OwnerControl({write}){const [platform,setPlatform]=useState('telegram');const [platformUserId,setPlatformUserId]=useState('');const [enabled,setEnabled]=useState('on');return <div className="fields"><Select label="Platform" options={['telegram','discord']} value={platform} onChange={event=>setPlatform(event.target.value)}/><Field label="Platform user ID" value={platformUserId} onChange={event=>setPlatformUserId(event.target.value)}/><Select label="Owner status" options={['on','off']} value={enabled} onChange={event=>setEnabled(event.target.value)}/><ConfirmAction label="Change owner status" warning="This changes global owner access. The final owner can never be removed." onConfirm={()=>write('owner',{platform,platformUserId,enabled,confirmation:'CONFIRM'})}/></div>}

export default function Admin({profile}){const overview=useLoad('/api/admin');const [error,setError]=useState('');const [ok,setOk]=useState('');const [effective,setEffective]=useState(null);
  async function write(action,value){setError('');setOk('');try{const result=await api(`/api/admin/${action}`,{method:'POST',body:JSON.stringify(value)});setOk(result.message);await overview.load();return result;}catch(reason){setError(reason.message);throw reason;}}
  async function formWrite(event,action){event.preventDefault();const form=event.currentTarget;try{await write(action,Object.fromEntries(new FormData(form)));}catch{}}
  async function submitterWrite(event){return formWrite(event,event.nativeEvent.submitter.value);}
  async function inspect(event){event.preventDefault();try{const query=new URLSearchParams(Object.fromEntries(new FormData(event.currentTarget)));setEffective(await api(`/api/admin/effective?${query}`));}catch(reason){setError(reason.message);}}
  const data=overview.data;return <><div className="page-title"><p className="eyebrow">Owner controls</p><h1>Admin &amp; Governance</h1><p>Manage the existing M7a groups, user ceilings, simulation rules, presets, and owners.</p></div>{(error||overview.error)&&<p className="notice error" role="alert">{error||overview.error}</p>}{ok&&<p className="notice ok" role="status">{ok}</p>}<p className="warning">Effective limits remain individual override → seat group → conservative M7 default. Forced simulation always wins.</p>
  <section><h2>Groups</h2><div className="card-grid">{data?.groups.map(group=><article className="card" key={group.name}><h2>{group.name}</h2><p>{group.maxTransactionValueWei} wei/tx<br/>{group.dailySpendingBudgetWei} wei/day<br/>{group.gasCeilingGwei} gwei gas</p><p>Simulation: {simulation(group.simulationForced)}</p><ConfirmAction label="Delete group" warning={`Delete ${group.name}? Assigned users will fall back to an individual override or M7 defaults.`} onConfirm={()=>write('group-delete',{name:group.name,confirmation:'CONFIRM'})}/></article>)}</div><Form title="Create or edit group" note="Editing a group updates effective limits for assigned users immediately." onSubmit={event=>formWrite(event,'group-set')}><Field name="name" label="Group name"/><Field name="maxWei" label="Maximum value (wei)"/><Field name="dailyWei" label="Daily budget (wei)"/><Field name="gasGwei" label="Gas ceiling (gwei)" type="number" step="any"/><Select name="simulation" label="Simulation" options={['forced','optional']}/><button>Save group</button></Form></section>
  <section><h2>Users and ceilings</h2><div className="card-grid">{data?.users.map(user=>{const account=identity(user);return <article className="card" key={user.userId}><span className="pill">{user.isOwner?'owner':'user'}</span><h2>{account?`${account.platform}:${account.platformUserId}`:user.userId}</h2><p>Group: {user.groupName||'none'}<br/>Preset: {user.selectedPresetKey||'none'}<br/>Simulation override: {simulation(user.simulationForced)}</p>{user.isOwner?<p className="ok">Owner — exempt from value, daily, and gas ceilings.</p>:<p>Overrides: {user.maxTransactionValueWei??'inherit'} wei/tx, {user.dailySpendingBudgetWei??'inherit'} wei/day, {user.gasCeilingGwei??'inherit'} gwei</p>}</article>})}</div><div className="form-grid"><Form title="Assign or unassign group" onSubmit={submitterWrite}><Select name="platform" label="Platform" options={['telegram','discord']}/><Field name="platformUserId" label="Platform user ID"/><Select name="group" label="Group" options={data?.groups.map(group=>group.name)||[]}/><button name="action" value="assign">Assign</button><button className="quiet" name="action" value="unassign">Unassign</button></Form><Form title="User ceiling override" note="Owners are exempt; these values apply to regular users." onSubmit={submitterWrite}><Select name="platform" label="Platform" options={['telegram','discord']}/><Field name="platformUserId" label="Platform user ID"/><Field name="maxWei" label="Maximum value (wei)"/><Field name="dailyWei" label="Daily budget (wei)"/><Field name="gasGwei" label="Gas ceiling (gwei)" type="number" step="any"/><button name="action" value="user-ceilings">Save override</button><button className="quiet" name="action" value="user-ceilings-clear">Clear override</button></Form><Form title="User simulation" onSubmit={event=>formWrite(event,'user-simulation')}><Select name="platform" label="Platform" options={['telegram','discord']}/><Field name="platformUserId" label="Platform user ID"/><Select name="simulation" label="Simulation" options={['forced','optional','inherit']}/><button>Save user rule</button></Form><Form title="Group simulation" onSubmit={event=>formWrite(event,'group-simulation')}><Select name="group" label="Group" options={data?.groups.map(group=>group.name)||[]}/><Select name="simulation" label="Simulation" options={['forced','optional','inherit']}/><button>Save group rule</button></Form></div></section>
  <section><h2>Effective governance lookup</h2><Form title="Inspect linked user" note="This read uses the same resolver as transaction policy enforcement." onSubmit={inspect}><Select name="platform" label="Platform" options={['telegram','discord']}/><Field name="platformUserId" label="Platform user ID"/><Select name="chain" label="Chain" options={profile.supportedChains}/><button>Read effective limits</button></Form>{effective&&<article className="panel effective-read" aria-live="polite"><h2>Effective result</h2>{effective.ceilingExempt?<p className="ok">Owner — exempt from value, daily, and gas ceilings.</p>:<p>{effective.maxTransactionValueWei} wei/tx | {effective.dailySpendingBudgetWei} wei/day | {effective.gasCeilingGwei} gwei gas</p>}<p>Simulation: {effective.simulationForced?'forced':'optional'}</p></article>}</section>
  <section><h2>Mode presets</h2><p>Human verification is preparatory per-target configuration. A preset never bypasses verification by itself; M10c still requires its explicit CONFIRM challenge.</p><div className="card-grid">{data?.presets.map(preset=><Form key={`${preset.key}:${preset.simulationMode}:${preset.confirmationCount}:${preset.humanVerification}`} title={preset.displayName} onSubmit={event=>formWrite(event,'preset-set')}><input type="hidden" name="preset" value={preset.key}/><Select name="simulation" label="Simulation" options={['on','off','blockchain_off']} defaultValue={preset.simulationMode}/><Field name="confirmations" label="Confirmations" type="number" min="1" max="1000" defaultValue={preset.confirmationCount}/><Select name="verification" label="Verification" options={['on','bypass']} defaultValue={preset.humanVerification}/><button>Save preset</button></Form>)}</div></section>
  <section><h2>Owner access</h2><div className="panel"><p className="warning">Owner changes affect global administration rights and require explicit confirmation.</p><OwnerControl write={write}/></div></section></>}
